import type { Table, Column, Relationship, Index } from "@whiteboard/types";

interface MySQLExportOptions {
  includeDropStatements: boolean;
  includeIfNotExists: boolean;
  includeComments: boolean;
  engine?: string;
  charset?: string;
  collation?: string;
  formatSql: boolean;
}

const defaultOptions: MySQLExportOptions = {
  includeDropStatements: false,
  includeIfNotExists: true,
  includeComments: true,
  engine: "InnoDB",
  charset: "utf8mb4",
  collation: "utf8mb4_unicode_ci",
  formatSql: true,
};

export function generateMySQLDDL(
  tables: Table[],
  columns: Map<string, Column[]>,
  relationships: Relationship[],
  indexes: Index[],
  options: Partial<MySQLExportOptions> = {}
): string {
  const opts = { ...defaultOptions, ...options };
  const lines: string[] = [];

  // Header comment
  lines.push("-- Generated by Whiteboard Database Designer");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Database: MySQL`);
  lines.push("");

  // Drop statements (in reverse order for dependencies)
  if (opts.includeDropStatements) {
    lines.push("-- Drop existing tables (if any)");
    lines.push("SET FOREIGN_KEY_CHECKS = 0;");
    for (const table of [...tables].reverse()) {
      lines.push(`DROP TABLE IF EXISTS \`${table.name}\`;`);
    }
    lines.push("SET FOREIGN_KEY_CHECKS = 1;");
    lines.push("");
  }

  // Create tables
  for (const table of tables) {
    const tableColumns = columns.get(table.id) || [];
    const tableRelationships = relationships.filter(
      (r) => r.sourceTableId === table.id
    );
    const tableIndexes = indexes.filter((i) => i.tableId === table.id);
    const tableDDL = generateTableDDL(
      table,
      tableColumns,
      tableRelationships,
      tableIndexes,
      tables,
      columns,
      opts
    );
    lines.push(tableDDL);
    lines.push("");
  }

  return lines.join("\n");
}

function generateTableDDL(
  table: Table,
  tableColumns: Column[],
  tableRelationships: Relationship[],
  tableIndexes: Index[],
  allTables: Table[],
  allColumns: Map<string, Column[]>,
  opts: MySQLExportOptions
): string {
  const lines: string[] = [];
  const indent = opts.formatSql ? "  " : "";

  // CREATE TABLE statement
  const ifNotExists = opts.includeIfNotExists ? "IF NOT EXISTS " : "";
  lines.push(`CREATE TABLE ${ifNotExists}\`${table.name}\` (`);

  // Columns
  const columnDefs: string[] = [];
  const primaryKeys: string[] = [];

  for (const col of tableColumns.sort((a, b) => a.ordinalPosition - b.ordinalPosition)) {
    let colDef = `${indent}\`${col.name}\` ${mapToMySQLType(col)}`;

    // NOT NULL
    if (!col.isNullable) {
      colDef += " NOT NULL";
    }

    // AUTO_INCREMENT
    const options = col.options as { autoIncrement?: boolean; onUpdate?: string };
    if (options.autoIncrement) {
      colDef += " AUTO_INCREMENT";
    }

    // DEFAULT
    if (col.defaultValue) {
      colDef += ` DEFAULT ${col.defaultValue}`;
    }

    // ON UPDATE (for TIMESTAMP)
    if (options.onUpdate) {
      colDef += ` ON UPDATE ${options.onUpdate}`;
    }

    // UNIQUE (non-primary key)
    if (col.isUnique && !col.isPrimaryKey) {
      colDef += " UNIQUE";
    }

    // Comment
    if (opts.includeComments && col.description) {
      colDef += ` COMMENT '${col.description.replace(/'/g, "''")}'`;
    }

    columnDefs.push(colDef);

    if (col.isPrimaryKey) {
      primaryKeys.push(`\`${col.name}\``);
    }
  }

  // Add PRIMARY KEY constraint
  if (primaryKeys.length > 0) {
    columnDefs.push(`${indent}PRIMARY KEY (${primaryKeys.join(", ")})`);
  }

  // Add indexes
  for (const index of tableIndexes) {
    const indexColumns = index.columnIds
      .map((id) => {
        const col = tableColumns.find((c) => c.id === id);
        return col ? `\`${col.name}\`` : null;
      })
      .filter(Boolean);

    if (indexColumns.length === 0) continue;

    if (index.isUnique) {
      columnDefs.push(
        `${indent}UNIQUE KEY \`${index.name}\` (${indexColumns.join(", ")})`
      );
    } else {
      columnDefs.push(
        `${indent}KEY \`${index.name}\` (${indexColumns.join(", ")})`
      );
    }
  }

  // Add foreign key constraints
  for (const rel of tableRelationships) {
    const targetTable = allTables.find((t) => t.id === rel.targetTableId);
    const targetColumns = allColumns.get(rel.targetTableId) || [];
    const sourceCol = tableColumns.find((c) => c.id === rel.sourceColumnId);
    const targetCol = targetColumns.find((c) => c.id === rel.targetColumnId);

    if (!targetTable || !sourceCol || !targetCol) continue;

    const constraintName =
      rel.name || `fk_${table.name}_${sourceCol.name}`;

    let fkDef = `${indent}CONSTRAINT \`${constraintName}\` FOREIGN KEY (\`${sourceCol.name}\`) REFERENCES \`${targetTable.name}\` (\`${targetCol.name}\`)`;

    if (rel.onDelete && rel.onDelete !== "NO ACTION") {
      fkDef += ` ON DELETE ${rel.onDelete}`;
    }
    if (rel.onUpdate && rel.onUpdate !== "NO ACTION") {
      fkDef += ` ON UPDATE ${rel.onUpdate}`;
    }

    columnDefs.push(fkDef);
  }

  lines.push(columnDefs.join(",\n"));
  lines.push(
    `) ENGINE=${opts.engine} DEFAULT CHARSET=${opts.charset} COLLATE=${opts.collation}`
  );

  // Table comment
  if (opts.includeComments && table.description) {
    lines[lines.length - 1] += ` COMMENT='${table.description.replace(/'/g, "''")}'`;
  }

  lines[lines.length - 1] += ";";

  return lines.join("\n");
}

function mapToMySQLType(column: Column): string {
  const baseType = column.dataType.toLowerCase();
  const options = column.options as {
    length?: number;
    precision?: number;
    scale?: number;
    enumValues?: string[];
  };

  switch (baseType) {
    case "string":
    case "varchar":
      return options.length ? `VARCHAR(${options.length})` : "VARCHAR(255)";
    case "char":
      return options.length ? `CHAR(${options.length})` : "CHAR(1)";
    case "text":
      return "TEXT";
    case "mediumtext":
      return "MEDIUMTEXT";
    case "longtext":
      return "LONGTEXT";
    case "tinyint":
      return "TINYINT";
    case "smallint":
      return "SMALLINT";
    case "mediumint":
      return "MEDIUMINT";
    case "int":
    case "integer":
      return "INT";
    case "bigint":
      return "BIGINT";
    case "decimal":
    case "numeric":
      if (options.precision && options.scale) {
        return `DECIMAL(${options.precision}, ${options.scale})`;
      }
      return "DECIMAL(10, 2)";
    case "float":
      return "FLOAT";
    case "double":
      return "DOUBLE";
    case "boolean":
    case "bool":
      return "TINYINT(1)";
    case "date":
      return "DATE";
    case "time":
      return "TIME";
    case "datetime":
      return "DATETIME";
    case "timestamp":
      return "TIMESTAMP";
    case "year":
      return "YEAR";
    case "uuid":
      return "CHAR(36)";
    case "json":
      return "JSON";
    case "blob":
      return "BLOB";
    case "binary":
      return options.length ? `BINARY(${options.length})` : "BINARY(255)";
    case "varbinary":
      return options.length ? `VARBINARY(${options.length})` : "VARBINARY(255)";
    case "enum":
      if (options.enumValues && options.enumValues.length > 0) {
        const values = options.enumValues
          .map((v) => `'${v.replace(/'/g, "''")}'`)
          .join(", ");
        return `ENUM(${values})`;
      }
      return "VARCHAR(255)";
    default:
      return baseType.toUpperCase();
  }
}
