import type { Table, Column, Relationship, Index } from "@whiteboard/types";

interface PostgreSQLExportOptions {
  includeDropStatements: boolean;
  includeIfNotExists: boolean;
  includeComments: boolean;
  schemaName?: string;
  formatSql: boolean;
}

const defaultOptions: PostgreSQLExportOptions = {
  includeDropStatements: false,
  includeIfNotExists: true,
  includeComments: true,
  schemaName: "public",
  formatSql: true,
};

export function generatePostgreSQLDDL(
  tables: Table[],
  columns: Map<string, Column[]>,
  relationships: Relationship[],
  indexes: Index[],
  options: Partial<PostgreSQLExportOptions> = {}
): string {
  const opts = { ...defaultOptions, ...options };
  const lines: string[] = [];

  // Header comment
  lines.push("-- Generated by Whiteboard Database Designer");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Database: PostgreSQL`);
  lines.push("");

  // Create schema if needed
  if (opts.schemaName && opts.schemaName !== "public") {
    lines.push(`CREATE SCHEMA IF NOT EXISTS ${opts.schemaName};`);
    lines.push("");
  }

  // Drop statements (in reverse order for dependencies)
  if (opts.includeDropStatements) {
    lines.push("-- Drop existing tables (if any)");
    for (const table of [...tables].reverse()) {
      lines.push(
        `DROP TABLE IF EXISTS ${opts.schemaName}.${table.name} CASCADE;`
      );
    }
    lines.push("");
  }

  // Create tables
  for (const table of tables) {
    const tableColumns = columns.get(table.id) || [];
    const tableDDL = generateTableDDL(table, tableColumns, opts);
    lines.push(tableDDL);
    lines.push("");
  }

  // Add foreign key constraints
  const foreignKeys = generateForeignKeys(
    relationships,
    tables,
    columns,
    opts
  );
  if (foreignKeys) {
    lines.push("-- Foreign Key Constraints");
    lines.push(foreignKeys);
    lines.push("");
  }

  // Create indexes
  const indexDDL = generateIndexes(indexes, tables, columns, opts);
  if (indexDDL) {
    lines.push("-- Indexes");
    lines.push(indexDDL);
    lines.push("");
  }

  // Add comments
  if (opts.includeComments) {
    const commentsDDL = generateComments(tables, columns, opts);
    if (commentsDDL) {
      lines.push("-- Comments");
      lines.push(commentsDDL);
    }
  }

  return lines.join("\n");
}

function generateTableDDL(
  table: Table,
  tableColumns: Column[],
  opts: PostgreSQLExportOptions
): string {
  const lines: string[] = [];
  const indent = opts.formatSql ? "  " : "";

  // CREATE TABLE statement
  const ifNotExists = opts.includeIfNotExists ? "IF NOT EXISTS " : "";
  lines.push(
    `CREATE TABLE ${ifNotExists}${opts.schemaName}.${table.name} (`
  );

  // Columns
  const columnDefs: string[] = [];
  const primaryKeys: string[] = [];

  for (const col of tableColumns.sort((a, b) => a.ordinalPosition - b.ordinalPosition)) {
    let colDef = `${indent}${col.name} ${mapToPostgresType(col)}`;

    // NOT NULL
    if (!col.isNullable) {
      colDef += " NOT NULL";
    }

    // DEFAULT
    if (col.defaultValue) {
      colDef += ` DEFAULT ${col.defaultValue}`;
    }

    // UNIQUE (non-primary key)
    if (col.isUnique && !col.isPrimaryKey) {
      colDef += " UNIQUE";
    }

    // CHECK constraint
    if (col.checkConstraint) {
      colDef += ` CHECK (${col.checkConstraint})`;
    }

    columnDefs.push(colDef);

    if (col.isPrimaryKey) {
      primaryKeys.push(col.name);
    }
  }

  // Add PRIMARY KEY constraint
  if (primaryKeys.length > 0) {
    columnDefs.push(`${indent}PRIMARY KEY (${primaryKeys.join(", ")})`);
  }

  lines.push(columnDefs.join(",\n"));
  lines.push(");");

  return lines.join("\n");
}

function mapToPostgresType(column: Column): string {
  const baseType = column.dataType.toLowerCase();
  const options = column.options as {
    length?: number;
    precision?: number;
    scale?: number;
    autoIncrement?: boolean;
  };

  // Handle auto-increment
  if (options.autoIncrement) {
    if (baseType === "integer" || baseType === "int") {
      return "SERIAL";
    }
    if (baseType === "bigint") {
      return "BIGSERIAL";
    }
    if (baseType === "smallint") {
      return "SMALLSERIAL";
    }
  }

  // Map common types
  switch (baseType) {
    case "string":
    case "varchar":
      return options.length ? `VARCHAR(${options.length})` : "TEXT";
    case "char":
      return options.length ? `CHAR(${options.length})` : "CHAR(1)";
    case "text":
      return "TEXT";
    case "int":
    case "integer":
      return "INTEGER";
    case "bigint":
      return "BIGINT";
    case "smallint":
      return "SMALLINT";
    case "decimal":
    case "numeric":
      if (options.precision && options.scale) {
        return `NUMERIC(${options.precision}, ${options.scale})`;
      }
      return "NUMERIC";
    case "float":
    case "real":
      return "REAL";
    case "double":
    case "double precision":
      return "DOUBLE PRECISION";
    case "boolean":
    case "bool":
      return "BOOLEAN";
    case "date":
      return "DATE";
    case "time":
      return "TIME";
    case "datetime":
    case "timestamp":
      return "TIMESTAMP";
    case "timestamptz":
    case "timestamp with time zone":
      return "TIMESTAMP WITH TIME ZONE";
    case "uuid":
      return "UUID";
    case "json":
      return "JSON";
    case "jsonb":
      return "JSONB";
    case "bytea":
    case "binary":
      return "BYTEA";
    case "array":
      return "TEXT[]";
    default:
      return baseType.toUpperCase();
  }
}

function generateForeignKeys(
  relationships: Relationship[],
  tables: Table[],
  columns: Map<string, Column[]>,
  opts: PostgreSQLExportOptions
): string {
  const lines: string[] = [];

  for (const rel of relationships) {
    const sourceTable = tables.find((t) => t.id === rel.sourceTableId);
    const targetTable = tables.find((t) => t.id === rel.targetTableId);

    if (!sourceTable || !targetTable) continue;

    const sourceColumns = columns.get(rel.sourceTableId) || [];
    const targetColumns = columns.get(rel.targetTableId) || [];

    const sourceCol = sourceColumns.find((c) => c.id === rel.sourceColumnId);
    const targetCol = targetColumns.find((c) => c.id === rel.targetColumnId);

    if (!sourceCol || !targetCol) continue;

    const constraintName =
      rel.name || `fk_${sourceTable.name}_${sourceCol.name}`;

    lines.push(
      `ALTER TABLE ${opts.schemaName}.${sourceTable.name}`
    );
    lines.push(
      `  ADD CONSTRAINT ${constraintName}`
    );
    lines.push(
      `  FOREIGN KEY (${sourceCol.name})`
    );
    lines.push(
      `  REFERENCES ${opts.schemaName}.${targetTable.name} (${targetCol.name})`
    );

    const actions: string[] = [];
    if (rel.onDelete && rel.onDelete !== "NO ACTION") {
      actions.push(`ON DELETE ${rel.onDelete}`);
    }
    if (rel.onUpdate && rel.onUpdate !== "NO ACTION") {
      actions.push(`ON UPDATE ${rel.onUpdate}`);
    }

    if (actions.length > 0) {
      lines.push(`  ${actions.join(" ")};`);
    } else {
      lines[lines.length - 1] += ";";
    }

    lines.push("");
  }

  return lines.join("\n");
}

function generateIndexes(
  indexes: Index[],
  tables: Table[],
  columns: Map<string, Column[]>,
  opts: PostgreSQLExportOptions
): string {
  const lines: string[] = [];

  for (const index of indexes) {
    const table = tables.find((t) => t.id === index.tableId);
    if (!table) continue;

    const tableColumns = columns.get(index.tableId) || [];
    const indexColumns = index.columnIds
      .map((id) => tableColumns.find((c) => c.id === id)?.name)
      .filter(Boolean);

    if (indexColumns.length === 0) continue;

    const unique = index.isUnique ? "UNIQUE " : "";
    const method = index.type !== "btree" ? ` USING ${index.type}` : "";

    lines.push(
      `CREATE ${unique}INDEX ${index.name} ON ${opts.schemaName}.${table.name}${method} (${indexColumns.join(", ")});`
    );
  }

  return lines.join("\n");
}

function generateComments(
  tables: Table[],
  columns: Map<string, Column[]>,
  opts: PostgreSQLExportOptions
): string {
  const lines: string[] = [];

  for (const table of tables) {
    if (table.description) {
      lines.push(
        `COMMENT ON TABLE ${opts.schemaName}.${table.name} IS '${table.description.replace(/'/g, "''")}';`
      );
    }

    const tableColumns = columns.get(table.id) || [];
    for (const col of tableColumns) {
      if (col.description) {
        lines.push(
          `COMMENT ON COLUMN ${opts.schemaName}.${table.name}.${col.name} IS '${col.description.replace(/'/g, "''")}';`
        );
      }
    }
  }

  return lines.join("\n");
}
